// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMSJjgUDR_DL2YX2t-ZOEnvYy9dsc_Klg',
    appId: '1:912302282393:web:fdc4ee6151040ce39b8a08',
    messagingSenderId: '912302282393',
    projectId: 'dantri-clone',
    authDomain: 'dantri-clone.firebaseapp.com',
    storageBucket: 'dantri-clone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuiWsCvDUT7umOelSdf8-vBki3vE-4tCc',
    appId: '1:912302282393:android:083623304ce4edc09b8a08',
    messagingSenderId: '912302282393',
    projectId: 'dantri-clone',
    storageBucket: 'dantri-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1V7R87tuys3SpJdLoW0sSgMK0opis7hI',
    appId: '1:912302282393:ios:1da32e5fb0460a8f9b8a08',
    messagingSenderId: '912302282393',
    projectId: 'dantri-clone',
    storageBucket: 'dantri-clone.firebasestorage.app',
    iosBundleId: 'com.example.dantriClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1V7R87tuys3SpJdLoW0sSgMK0opis7hI',
    appId: '1:912302282393:ios:1da32e5fb0460a8f9b8a08',
    messagingSenderId: '912302282393',
    projectId: 'dantri-clone',
    storageBucket: 'dantri-clone.firebasestorage.app',
    iosBundleId: 'com.example.dantriClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMSJjgUDR_DL2YX2t-ZOEnvYy9dsc_Klg',
    appId: '1:912302282393:web:00b58d667157f02c9b8a08',
    messagingSenderId: '912302282393',
    projectId: 'dantri-clone',
    authDomain: 'dantri-clone.firebaseapp.com',
    storageBucket: 'dantri-clone.firebasestorage.app',
  );
}
